name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
category-template: '### $TITLE'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '💣 Breaking Change'
    label: 'breaking'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📝 Documentation'
    label: 'documentation'
  - title: '🔨 Maintenance'
    label: 'chore'
exclude-labels:
- 'skip-changelog'
change-template: '- $TITLE (#$NUMBER) [by @$AUTHOR]'
template: |
  ## New in CAGEnt v$RESOLVED_VERSION
  $CHANGES
replacers:
  - search: ' [by @gordonjb]'
    replace: ''
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'enhancement'
  default: patch
